name: Checkout repoB via ssh

on: [push, pull_request]

jobs:
  checkout:
    runs-on: windows-latest
    default:
      run:
        shell: bash
    steps:
    - name: install MSYS2
      uses: msys2/setup-msys2@v2
      with:
         update: false
         msystem: mingw64
         install: >-
           git
           ssh
    - name: repoA checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: repoB checkout
      run: |
        set -x
        ls repoB_*
        chmod 600 repoB_*
        git -c core.sshCommand='ssh -vvv -i repoB_deployment_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' clone -b main git@github.com:eudoxos/repoB.git repoB
        ls repoB/README.md
