name: Checkout repoB via ssh

on: [push, pull_request]

jobs:
  checkout-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: install MSYS2
      uses: msys2/setup-msys2@v2
      with:
         update: false
         msystem: mingw64
         install: >-
           git
           util-linux
           dos2unix
    - name: repoA checkout
      uses: actions/checkout@v2
    - name: repoB checkout
      run: |
        set -x
        ls repoB_*
        chmod 600 repoB_*
        dos2unix repoB_deployment_key
        # which hexdump
        # hexdump repoB_deployment_key
        # ssh-add repoB_deployment_key # suggested by https://serverfault.com/a/1095310
        git -c core.sshCommand='ssh -vvv -i repoB_deployment_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' clone -b main git@github.com:eudoxos/repoB.git repoB
        ls repoB/README.md
  checkout-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: repoA checkout
      uses: actions/checkout@v2
    - name: repoB checkout
      run: |
        set -x
        ls repoB_*
        chmod 600 repoB_*
        git -c core.sshCommand='ssh -vvv -i repoB_deployment_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' clone -b main git@github.com:eudoxos/repoB.git repoB
        ls repoB/README.md
